package priv.sunyj.sms.bean;

public class AuthPower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_power.auth_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String authNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_power.pow_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String powNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_power.pow_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String powName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_power.auth_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String authName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_power.auth_num
     *
     * @return the value of t_auth_power.auth_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getAuthNum() {
        return authNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_power.auth_num
     *
     * @param authNum the value for t_auth_power.auth_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setAuthNum(String authNum) {
        this.authNum = authNum == null ? null : authNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_power.pow_num
     *
     * @return the value of t_auth_power.pow_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getPowNum() {
        return powNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_power.pow_num
     *
     * @param powNum the value for t_auth_power.pow_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setPowNum(String powNum) {
        this.powNum = powNum == null ? null : powNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_power.pow_name
     *
     * @return the value of t_auth_power.pow_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getPowName() {
        return powName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_power.pow_name
     *
     * @param powName the value for t_auth_power.pow_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setPowName(String powName) {
        this.powName = powName == null ? null : powName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_power.auth_name
     *
     * @return the value of t_auth_power.auth_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_power.auth_name
     *
     * @param authName the value for t_auth_power.auth_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }
}