package priv.sunyj.sms.bean;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.a_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String aNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.a_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String aName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.a_num
     *
     * @return the value of t_auth.a_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getaNum() {
        return aNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.a_num
     *
     * @param aNum the value for t_auth.a_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setaNum(String aNum) {
        this.aNum = aNum == null ? null : aNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.a_name
     *
     * @return the value of t_auth.a_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.a_name
     *
     * @param aName the value for t_auth.a_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }
}