package priv.sunyj.sms.bean;

import java.util.ArrayList;
import java.util.List;

public class ClassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public ClassExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCNumIsNull() {
            addCriterion("c_num is null");
            return (Criteria) this;
        }

        public Criteria andCNumIsNotNull() {
            addCriterion("c_num is not null");
            return (Criteria) this;
        }

        public Criteria andCNumEqualTo(String value) {
            addCriterion("c_num =", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotEqualTo(String value) {
            addCriterion("c_num <>", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumGreaterThan(String value) {
            addCriterion("c_num >", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumGreaterThanOrEqualTo(String value) {
            addCriterion("c_num >=", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumLessThan(String value) {
            addCriterion("c_num <", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumLessThanOrEqualTo(String value) {
            addCriterion("c_num <=", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumLike(String value) {
            addCriterion("c_num like", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotLike(String value) {
            addCriterion("c_num not like", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumIn(List<String> values) {
            addCriterion("c_num in", values, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotIn(List<String> values) {
            addCriterion("c_num not in", values, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumBetween(String value1, String value2) {
            addCriterion("c_num between", value1, value2, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotBetween(String value1, String value2) {
            addCriterion("c_num not between", value1, value2, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andKey1IsNull() {
            addCriterion("key1 is null");
            return (Criteria) this;
        }

        public Criteria andKey1IsNotNull() {
            addCriterion("key1 is not null");
            return (Criteria) this;
        }

        public Criteria andKey1EqualTo(String value) {
            addCriterion("key1 =", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotEqualTo(String value) {
            addCriterion("key1 <>", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1GreaterThan(String value) {
            addCriterion("key1 >", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1GreaterThanOrEqualTo(String value) {
            addCriterion("key1 >=", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1LessThan(String value) {
            addCriterion("key1 <", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1LessThanOrEqualTo(String value) {
            addCriterion("key1 <=", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1Like(String value) {
            addCriterion("key1 like", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotLike(String value) {
            addCriterion("key1 not like", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1In(List<String> values) {
            addCriterion("key1 in", values, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotIn(List<String> values) {
            addCriterion("key1 not in", values, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1Between(String value1, String value2) {
            addCriterion("key1 between", value1, value2, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotBetween(String value1, String value2) {
            addCriterion("key1 not between", value1, value2, "key1");
            return (Criteria) this;
        }

        public Criteria andCUserNumIsNull() {
            addCriterion("c_user_num is null");
            return (Criteria) this;
        }

        public Criteria andCUserNumIsNotNull() {
            addCriterion("c_user_num is not null");
            return (Criteria) this;
        }

        public Criteria andCUserNumEqualTo(String value) {
            addCriterion("c_user_num =", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumNotEqualTo(String value) {
            addCriterion("c_user_num <>", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumGreaterThan(String value) {
            addCriterion("c_user_num >", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumGreaterThanOrEqualTo(String value) {
            addCriterion("c_user_num >=", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumLessThan(String value) {
            addCriterion("c_user_num <", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumLessThanOrEqualTo(String value) {
            addCriterion("c_user_num <=", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumLike(String value) {
            addCriterion("c_user_num like", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumNotLike(String value) {
            addCriterion("c_user_num not like", value, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumIn(List<String> values) {
            addCriterion("c_user_num in", values, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumNotIn(List<String> values) {
            addCriterion("c_user_num not in", values, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumBetween(String value1, String value2) {
            addCriterion("c_user_num between", value1, value2, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCUserNumNotBetween(String value1, String value2) {
            addCriterion("c_user_num not between", value1, value2, "cUserNum");
            return (Criteria) this;
        }

        public Criteria andCMajorIsNull() {
            addCriterion("c_major is null");
            return (Criteria) this;
        }

        public Criteria andCMajorIsNotNull() {
            addCriterion("c_major is not null");
            return (Criteria) this;
        }

        public Criteria andCMajorEqualTo(String value) {
            addCriterion("c_major =", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorNotEqualTo(String value) {
            addCriterion("c_major <>", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorGreaterThan(String value) {
            addCriterion("c_major >", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorGreaterThanOrEqualTo(String value) {
            addCriterion("c_major >=", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorLessThan(String value) {
            addCriterion("c_major <", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorLessThanOrEqualTo(String value) {
            addCriterion("c_major <=", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorLike(String value) {
            addCriterion("c_major like", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorNotLike(String value) {
            addCriterion("c_major not like", value, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorIn(List<String> values) {
            addCriterion("c_major in", values, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorNotIn(List<String> values) {
            addCriterion("c_major not in", values, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorBetween(String value1, String value2) {
            addCriterion("c_major between", value1, value2, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCMajorNotBetween(String value1, String value2) {
            addCriterion("c_major not between", value1, value2, "cMajor");
            return (Criteria) this;
        }

        public Criteria andCInsIsNull() {
            addCriterion("c_ins is null");
            return (Criteria) this;
        }

        public Criteria andCInsIsNotNull() {
            addCriterion("c_ins is not null");
            return (Criteria) this;
        }

        public Criteria andCInsEqualTo(String value) {
            addCriterion("c_ins =", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotEqualTo(String value) {
            addCriterion("c_ins <>", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsGreaterThan(String value) {
            addCriterion("c_ins >", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsGreaterThanOrEqualTo(String value) {
            addCriterion("c_ins >=", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsLessThan(String value) {
            addCriterion("c_ins <", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsLessThanOrEqualTo(String value) {
            addCriterion("c_ins <=", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsLike(String value) {
            addCriterion("c_ins like", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotLike(String value) {
            addCriterion("c_ins not like", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsIn(List<String> values) {
            addCriterion("c_ins in", values, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotIn(List<String> values) {
            addCriterion("c_ins not in", values, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsBetween(String value1, String value2) {
            addCriterion("c_ins between", value1, value2, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotBetween(String value1, String value2) {
            addCriterion("c_ins not between", value1, value2, "cIns");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbg.generated do_not_delete_during_merge Wed May 19 15:50:21 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}