package priv.sunyj.sms.bean;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.c_user_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cUserNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.c_major
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cIns;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.c_num
     *
     * @return the value of t_class.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcNum() {
        return cNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.c_num
     *
     * @param cNum the value for t_class.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcNum(String cNum) {
        this.cNum = cNum == null ? null : cNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.c_name
     *
     * @return the value of t_class.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.c_name
     *
     * @param cName the value for t_class.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.key1
     *
     * @return the value of t_class.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.key1
     *
     * @param key1 the value for t_class.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.c_user_num
     *
     * @return the value of t_class.c_user_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcUserNum() {
        return cUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.c_user_num
     *
     * @param cUserNum the value for t_class.c_user_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcUserNum(String cUserNum) {
        this.cUserNum = cUserNum == null ? null : cUserNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.c_major
     *
     * @return the value of t_class.c_major
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcMajor() {
        return cMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.c_major
     *
     * @param cMajor the value for t_class.c_major
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcMajor(String cMajor) {
        this.cMajor = cMajor == null ? null : cMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.c_ins
     *
     * @return the value of t_class.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcIns() {
        return cIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.c_ins
     *
     * @param cIns the value for t_class.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcIns(String cIns) {
        this.cIns = cIns == null ? null : cIns.trim();
    }
}