package priv.sunyj.sms.bean;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cIns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.is_sel
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String isSel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.c_gra
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cGra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.c_time
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.week
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cla;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.c_name
     *
     * @return the value of t_course.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.c_name
     *
     * @param cName the value for t_course.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.c_num
     *
     * @return the value of t_course.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcNum() {
        return cNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.c_num
     *
     * @param cNum the value for t_course.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcNum(String cNum) {
        this.cNum = cNum == null ? null : cNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.key1
     *
     * @return the value of t_course.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.key1
     *
     * @param key1 the value for t_course.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.key2
     *
     * @return the value of t_course.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.key2
     *
     * @param key2 the value for t_course.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey2(String key2) {
        this.key2 = key2 == null ? null : key2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.key3
     *
     * @return the value of t_course.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey3() {
        return key3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.key3
     *
     * @param key3 the value for t_course.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey3(String key3) {
        this.key3 = key3 == null ? null : key3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.c_ins
     *
     * @return the value of t_course.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcIns() {
        return cIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.c_ins
     *
     * @param cIns the value for t_course.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcIns(String cIns) {
        this.cIns = cIns == null ? null : cIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.is_sel
     *
     * @return the value of t_course.is_sel
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getIsSel() {
        return isSel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.is_sel
     *
     * @param isSel the value for t_course.is_sel
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setIsSel(String isSel) {
        this.isSel = isSel == null ? null : isSel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.c_gra
     *
     * @return the value of t_course.c_gra
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcGra() {
        return cGra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.c_gra
     *
     * @param cGra the value for t_course.c_gra
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcGra(String cGra) {
        this.cGra = cGra == null ? null : cGra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.c_time
     *
     * @return the value of t_course.c_time
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.c_time
     *
     * @param cTime the value for t_course.c_time
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcTime(String cTime) {
        this.cTime = cTime == null ? null : cTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.week
     *
     * @return the value of t_course.week
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.week
     *
     * @param week the value for t_course.week
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.cla
     *
     * @return the value of t_course.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getCla() {
        return cla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.cla
     *
     * @param cla the value for t_course.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setCla(String cla) {
        this.cla = cla == null ? null : cla.trim();
    }
}