package priv.sunyj.sms.bean;

public class Institution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ins.i_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String iNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ins.i_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String iName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ins.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ins.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ins.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ins.i_num
     *
     * @return the value of t_ins.i_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getiNum() {
        return iNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ins.i_num
     *
     * @param iNum the value for t_ins.i_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setiNum(String iNum) {
        this.iNum = iNum == null ? null : iNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ins.i_name
     *
     * @return the value of t_ins.i_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getiName() {
        return iName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ins.i_name
     *
     * @param iName the value for t_ins.i_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setiName(String iName) {
        this.iName = iName == null ? null : iName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ins.key1
     *
     * @return the value of t_ins.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ins.key1
     *
     * @param key1 the value for t_ins.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ins.key2
     *
     * @return the value of t_ins.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ins.key2
     *
     * @param key2 the value for t_ins.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey2(String key2) {
        this.key2 = key2 == null ? null : key2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ins.key3
     *
     * @return the value of t_ins.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey3() {
        return key3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ins.key3
     *
     * @param key3 the value for t_ins.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey3(String key3) {
        this.key3 = key3 == null ? null : key3.trim();
    }
}