package priv.sunyj.sms.bean;

public class MajCour {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maj_cour.maj_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String majName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maj_cour.cour_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String courName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maj_cour.cour_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String courIns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maj_cour.year
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maj_cour.school
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String school;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maj_cour.maj_name
     *
     * @return the value of t_maj_cour.maj_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getMajName() {
        return majName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maj_cour.maj_name
     *
     * @param majName the value for t_maj_cour.maj_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setMajName(String majName) {
        this.majName = majName == null ? null : majName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maj_cour.cour_name
     *
     * @return the value of t_maj_cour.cour_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getCourName() {
        return courName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maj_cour.cour_name
     *
     * @param courName the value for t_maj_cour.cour_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setCourName(String courName) {
        this.courName = courName == null ? null : courName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maj_cour.cour_ins
     *
     * @return the value of t_maj_cour.cour_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getCourIns() {
        return courIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maj_cour.cour_ins
     *
     * @param courIns the value for t_maj_cour.cour_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setCourIns(String courIns) {
        this.courIns = courIns == null ? null : courIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maj_cour.year
     *
     * @return the value of t_maj_cour.year
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maj_cour.year
     *
     * @param year the value for t_maj_cour.year
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maj_cour.school
     *
     * @return the value of t_maj_cour.school
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maj_cour.school
     *
     * @param school the value for t_maj_cour.school
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }
}