package priv.sunyj.sms.bean;

public class MajCla {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maj_cla.maj_num
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    private String majNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_maj_cla.cla_num
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    private String claNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maj_cla.maj_num
     *
     * @return the value of t_maj_cla.maj_num
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public String getMajNum() {
        return majNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maj_cla.maj_num
     *
     * @param majNum the value for t_maj_cla.maj_num
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public void setMajNum(String majNum) {
        this.majNum = majNum == null ? null : majNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_maj_cla.cla_num
     *
     * @return the value of t_maj_cla.cla_num
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public String getClaNum() {
        return claNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_maj_cla.cla_num
     *
     * @param claNum the value for t_maj_cla.cla_num
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public void setClaNum(String claNum) {
        this.claNum = claNum == null ? null : claNum.trim();
    }
}