package priv.sunyj.sms.bean;

import java.util.ArrayList;
import java.util.List;

public class MajClaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public MajClaExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMajNumIsNull() {
            addCriterion("maj_num is null");
            return (Criteria) this;
        }

        public Criteria andMajNumIsNotNull() {
            addCriterion("maj_num is not null");
            return (Criteria) this;
        }

        public Criteria andMajNumEqualTo(String value) {
            addCriterion("maj_num =", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumNotEqualTo(String value) {
            addCriterion("maj_num <>", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumGreaterThan(String value) {
            addCriterion("maj_num >", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumGreaterThanOrEqualTo(String value) {
            addCriterion("maj_num >=", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumLessThan(String value) {
            addCriterion("maj_num <", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumLessThanOrEqualTo(String value) {
            addCriterion("maj_num <=", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumLike(String value) {
            addCriterion("maj_num like", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumNotLike(String value) {
            addCriterion("maj_num not like", value, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumIn(List<String> values) {
            addCriterion("maj_num in", values, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumNotIn(List<String> values) {
            addCriterion("maj_num not in", values, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumBetween(String value1, String value2) {
            addCriterion("maj_num between", value1, value2, "majNum");
            return (Criteria) this;
        }

        public Criteria andMajNumNotBetween(String value1, String value2) {
            addCriterion("maj_num not between", value1, value2, "majNum");
            return (Criteria) this;
        }

        public Criteria andClaNumIsNull() {
            addCriterion("cla_num is null");
            return (Criteria) this;
        }

        public Criteria andClaNumIsNotNull() {
            addCriterion("cla_num is not null");
            return (Criteria) this;
        }

        public Criteria andClaNumEqualTo(String value) {
            addCriterion("cla_num =", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumNotEqualTo(String value) {
            addCriterion("cla_num <>", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumGreaterThan(String value) {
            addCriterion("cla_num >", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumGreaterThanOrEqualTo(String value) {
            addCriterion("cla_num >=", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumLessThan(String value) {
            addCriterion("cla_num <", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumLessThanOrEqualTo(String value) {
            addCriterion("cla_num <=", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumLike(String value) {
            addCriterion("cla_num like", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumNotLike(String value) {
            addCriterion("cla_num not like", value, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumIn(List<String> values) {
            addCriterion("cla_num in", values, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumNotIn(List<String> values) {
            addCriterion("cla_num not in", values, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumBetween(String value1, String value2) {
            addCriterion("cla_num between", value1, value2, "claNum");
            return (Criteria) this;
        }

        public Criteria andClaNumNotBetween(String value1, String value2) {
            addCriterion("cla_num not between", value1, value2, "claNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maj_cla
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 27 19:50:03 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}