package priv.sunyj.sms.bean;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.m_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String mNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.m_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.m_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String mIns;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.m_num
     *
     * @return the value of t_major.m_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getmNum() {
        return mNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.m_num
     *
     * @param mNum the value for t_major.m_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setmNum(String mNum) {
        this.mNum = mNum == null ? null : mNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.m_name
     *
     * @return the value of t_major.m_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.m_name
     *
     * @param mName the value for t_major.m_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.key1
     *
     * @return the value of t_major.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.key1
     *
     * @param key1 the value for t_major.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.key2
     *
     * @return the value of t_major.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.key2
     *
     * @param key2 the value for t_major.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey2(String key2) {
        this.key2 = key2 == null ? null : key2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.key3
     *
     * @return the value of t_major.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey3() {
        return key3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.key3
     *
     * @param key3 the value for t_major.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey3(String key3) {
        this.key3 = key3 == null ? null : key3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.m_ins
     *
     * @return the value of t_major.m_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getmIns() {
        return mIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.m_ins
     *
     * @param mIns the value for t_major.m_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setmIns(String mIns) {
        this.mIns = mIns == null ? null : mIns.trim();
    }
}