package priv.sunyj.sms.bean;

public class Pow1Pow2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pow1_pow2.pow1_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    private String pow1Num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pow1_pow2.pow2_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    private String pow2Num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pow1_pow2.pow1_num
     *
     * @return the value of t_pow1_pow2.pow1_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public String getPow1Num() {
        return pow1Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pow1_pow2.pow1_num
     *
     * @param pow1Num the value for t_pow1_pow2.pow1_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public void setPow1Num(String pow1Num) {
        this.pow1Num = pow1Num == null ? null : pow1Num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pow1_pow2.pow2_num
     *
     * @return the value of t_pow1_pow2.pow2_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public String getPow2Num() {
        return pow2Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pow1_pow2.pow2_num
     *
     * @param pow2Num the value for t_pow1_pow2.pow2_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public void setPow2Num(String pow2Num) {
        this.pow2Num = pow2Num == null ? null : pow2Num.trim();
    }
}