package priv.sunyj.sms.bean;

public class Power2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_power_2.p_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    private String pNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_power_2.p_name
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_power_2.key1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_power_2.key2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    private String key2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_power_2.key3
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    private String key3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_power_2.p_num
     *
     * @return the value of t_power_2.p_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public String getpNum() {
        return pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_power_2.p_num
     *
     * @param pNum the value for t_power_2.p_num
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public void setpNum(String pNum) {
        this.pNum = pNum == null ? null : pNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_power_2.p_name
     *
     * @return the value of t_power_2.p_name
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_power_2.p_name
     *
     * @param pName the value for t_power_2.p_name
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_power_2.key1
     *
     * @return the value of t_power_2.key1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_power_2.key1
     *
     * @param key1 the value for t_power_2.key1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_power_2.key2
     *
     * @return the value of t_power_2.key2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_power_2.key2
     *
     * @param key2 the value for t_power_2.key2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public void setKey2(String key2) {
        this.key2 = key2 == null ? null : key2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_power_2.key3
     *
     * @return the value of t_power_2.key3
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public String getKey3() {
        return key3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_power_2.key3
     *
     * @param key3 the value for t_power_2.key3
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    public void setKey3(String key3) {
        this.key3 = key3 == null ? null : key3.trim();
    }
}