package priv.sunyj.sms.bean;

public class StuCour {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_cour.stu_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_cour.cour_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String courName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_cour.year
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_cour.school
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_cour.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_cour.grade
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_cour.num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_cour.stu_name
     *
     * @return the value of t_stu_cour.stu_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_cour.stu_name
     *
     * @param stuName the value for t_stu_cour.stu_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_cour.cour_name
     *
     * @return the value of t_stu_cour.cour_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getCourName() {
        return courName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_cour.cour_name
     *
     * @param courName the value for t_stu_cour.cour_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setCourName(String courName) {
        this.courName = courName == null ? null : courName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_cour.year
     *
     * @return the value of t_stu_cour.year
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_cour.year
     *
     * @param year the value for t_stu_cour.year
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_cour.school
     *
     * @return the value of t_stu_cour.school
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_cour.school
     *
     * @param school the value for t_stu_cour.school
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_cour.cla
     *
     * @return the value of t_stu_cour.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getCla() {
        return cla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_cour.cla
     *
     * @param cla the value for t_stu_cour.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setCla(String cla) {
        this.cla = cla == null ? null : cla.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_cour.grade
     *
     * @return the value of t_stu_cour.grade
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_cour.grade
     *
     * @param grade the value for t_stu_cour.grade
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_cour.num
     *
     * @return the value of t_stu_cour.num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_cour.num
     *
     * @param num the value for t_stu_cour.num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }
}