package priv.sunyj.sms.bean;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_sex
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_email
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_phone
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_addr
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_pic
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_state
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_in
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_birth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sIns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_maj
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sMaj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sCla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_auth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.s_pwd
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_num
     *
     * @return the value of t_stu.s_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsNum() {
        return sNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_num
     *
     * @param sNum the value for t_stu.s_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsNum(String sNum) {
        this.sNum = sNum == null ? null : sNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_name
     *
     * @return the value of t_stu.s_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_name
     *
     * @param sName the value for t_stu.s_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_sex
     *
     * @return the value of t_stu.s_sex
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_sex
     *
     * @param sSex the value for t_stu.s_sex
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsSex(String sSex) {
        this.sSex = sSex == null ? null : sSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_email
     *
     * @return the value of t_stu.s_email
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsEmail() {
        return sEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_email
     *
     * @param sEmail the value for t_stu.s_email
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsEmail(String sEmail) {
        this.sEmail = sEmail == null ? null : sEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_phone
     *
     * @return the value of t_stu.s_phone
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_phone
     *
     * @param sPhone the value for t_stu.s_phone
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_addr
     *
     * @return the value of t_stu.s_addr
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsAddr() {
        return sAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_addr
     *
     * @param sAddr the value for t_stu.s_addr
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsAddr(String sAddr) {
        this.sAddr = sAddr == null ? null : sAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_pic
     *
     * @return the value of t_stu.s_pic
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsPic() {
        return sPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_pic
     *
     * @param sPic the value for t_stu.s_pic
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsPic(String sPic) {
        this.sPic = sPic == null ? null : sPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_state
     *
     * @return the value of t_stu.s_state
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsState() {
        return sState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_state
     *
     * @param sState the value for t_stu.s_state
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsState(String sState) {
        this.sState = sState == null ? null : sState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_in
     *
     * @return the value of t_stu.s_in
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsIn() {
        return sIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_in
     *
     * @param sIn the value for t_stu.s_in
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsIn(String sIn) {
        this.sIn = sIn == null ? null : sIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_birth
     *
     * @return the value of t_stu.s_birth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsBirth() {
        return sBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_birth
     *
     * @param sBirth the value for t_stu.s_birth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsBirth(String sBirth) {
        this.sBirth = sBirth == null ? null : sBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.key1
     *
     * @return the value of t_stu.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.key1
     *
     * @param key1 the value for t_stu.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.key2
     *
     * @return the value of t_stu.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.key2
     *
     * @param key2 the value for t_stu.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey2(String key2) {
        this.key2 = key2 == null ? null : key2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.key3
     *
     * @return the value of t_stu.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey3() {
        return key3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.key3
     *
     * @param key3 the value for t_stu.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey3(String key3) {
        this.key3 = key3 == null ? null : key3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_ins
     *
     * @return the value of t_stu.s_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsIns() {
        return sIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_ins
     *
     * @param sIns the value for t_stu.s_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsIns(String sIns) {
        this.sIns = sIns == null ? null : sIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_maj
     *
     * @return the value of t_stu.s_maj
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsMaj() {
        return sMaj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_maj
     *
     * @param sMaj the value for t_stu.s_maj
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsMaj(String sMaj) {
        this.sMaj = sMaj == null ? null : sMaj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_cla
     *
     * @return the value of t_stu.s_cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsCla() {
        return sCla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_cla
     *
     * @param sCla the value for t_stu.s_cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsCla(String sCla) {
        this.sCla = sCla == null ? null : sCla.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_auth
     *
     * @return the value of t_stu.s_auth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsAuth() {
        return sAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_auth
     *
     * @param sAuth the value for t_stu.s_auth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsAuth(String sAuth) {
        this.sAuth = sAuth == null ? null : sAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.s_pwd
     *
     * @return the value of t_stu.s_pwd
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsPwd() {
        return sPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.s_pwd
     *
     * @param sPwd the value for t_stu.s_pwd
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsPwd(String sPwd) {
        this.sPwd = sPwd == null ? null : sPwd.trim();
    }
}