package priv.sunyj.sms.bean;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public StudentExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSNumIsNull() {
            addCriterion("s_num is null");
            return (Criteria) this;
        }

        public Criteria andSNumIsNotNull() {
            addCriterion("s_num is not null");
            return (Criteria) this;
        }

        public Criteria andSNumEqualTo(String value) {
            addCriterion("s_num =", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotEqualTo(String value) {
            addCriterion("s_num <>", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumGreaterThan(String value) {
            addCriterion("s_num >", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumGreaterThanOrEqualTo(String value) {
            addCriterion("s_num >=", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumLessThan(String value) {
            addCriterion("s_num <", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumLessThanOrEqualTo(String value) {
            addCriterion("s_num <=", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumLike(String value) {
            addCriterion("s_num like", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotLike(String value) {
            addCriterion("s_num not like", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumIn(List<String> values) {
            addCriterion("s_num in", values, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotIn(List<String> values) {
            addCriterion("s_num not in", values, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumBetween(String value1, String value2) {
            addCriterion("s_num between", value1, value2, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotBetween(String value1, String value2) {
            addCriterion("s_num not between", value1, value2, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNameIsNull() {
            addCriterion("s_name is null");
            return (Criteria) this;
        }

        public Criteria andSNameIsNotNull() {
            addCriterion("s_name is not null");
            return (Criteria) this;
        }

        public Criteria andSNameEqualTo(String value) {
            addCriterion("s_name =", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotEqualTo(String value) {
            addCriterion("s_name <>", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThan(String value) {
            addCriterion("s_name >", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThanOrEqualTo(String value) {
            addCriterion("s_name >=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThan(String value) {
            addCriterion("s_name <", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThanOrEqualTo(String value) {
            addCriterion("s_name <=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLike(String value) {
            addCriterion("s_name like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotLike(String value) {
            addCriterion("s_name not like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameIn(List<String> values) {
            addCriterion("s_name in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotIn(List<String> values) {
            addCriterion("s_name not in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameBetween(String value1, String value2) {
            addCriterion("s_name between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotBetween(String value1, String value2) {
            addCriterion("s_name not between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSSexIsNull() {
            addCriterion("s_sex is null");
            return (Criteria) this;
        }

        public Criteria andSSexIsNotNull() {
            addCriterion("s_sex is not null");
            return (Criteria) this;
        }

        public Criteria andSSexEqualTo(String value) {
            addCriterion("s_sex =", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexNotEqualTo(String value) {
            addCriterion("s_sex <>", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexGreaterThan(String value) {
            addCriterion("s_sex >", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexGreaterThanOrEqualTo(String value) {
            addCriterion("s_sex >=", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexLessThan(String value) {
            addCriterion("s_sex <", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexLessThanOrEqualTo(String value) {
            addCriterion("s_sex <=", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexLike(String value) {
            addCriterion("s_sex like", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexNotLike(String value) {
            addCriterion("s_sex not like", value, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexIn(List<String> values) {
            addCriterion("s_sex in", values, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexNotIn(List<String> values) {
            addCriterion("s_sex not in", values, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexBetween(String value1, String value2) {
            addCriterion("s_sex between", value1, value2, "sSex");
            return (Criteria) this;
        }

        public Criteria andSSexNotBetween(String value1, String value2) {
            addCriterion("s_sex not between", value1, value2, "sSex");
            return (Criteria) this;
        }

        public Criteria andSEmailIsNull() {
            addCriterion("s_email is null");
            return (Criteria) this;
        }

        public Criteria andSEmailIsNotNull() {
            addCriterion("s_email is not null");
            return (Criteria) this;
        }

        public Criteria andSEmailEqualTo(String value) {
            addCriterion("s_email =", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailNotEqualTo(String value) {
            addCriterion("s_email <>", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailGreaterThan(String value) {
            addCriterion("s_email >", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailGreaterThanOrEqualTo(String value) {
            addCriterion("s_email >=", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailLessThan(String value) {
            addCriterion("s_email <", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailLessThanOrEqualTo(String value) {
            addCriterion("s_email <=", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailLike(String value) {
            addCriterion("s_email like", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailNotLike(String value) {
            addCriterion("s_email not like", value, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailIn(List<String> values) {
            addCriterion("s_email in", values, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailNotIn(List<String> values) {
            addCriterion("s_email not in", values, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailBetween(String value1, String value2) {
            addCriterion("s_email between", value1, value2, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSEmailNotBetween(String value1, String value2) {
            addCriterion("s_email not between", value1, value2, "sEmail");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNull() {
            addCriterion("s_phone is null");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNotNull() {
            addCriterion("s_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSPhoneEqualTo(String value) {
            addCriterion("s_phone =", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotEqualTo(String value) {
            addCriterion("s_phone <>", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThan(String value) {
            addCriterion("s_phone >", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("s_phone >=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThan(String value) {
            addCriterion("s_phone <", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThanOrEqualTo(String value) {
            addCriterion("s_phone <=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLike(String value) {
            addCriterion("s_phone like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotLike(String value) {
            addCriterion("s_phone not like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneIn(List<String> values) {
            addCriterion("s_phone in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotIn(List<String> values) {
            addCriterion("s_phone not in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneBetween(String value1, String value2) {
            addCriterion("s_phone between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotBetween(String value1, String value2) {
            addCriterion("s_phone not between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSAddrIsNull() {
            addCriterion("s_addr is null");
            return (Criteria) this;
        }

        public Criteria andSAddrIsNotNull() {
            addCriterion("s_addr is not null");
            return (Criteria) this;
        }

        public Criteria andSAddrEqualTo(String value) {
            addCriterion("s_addr =", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrNotEqualTo(String value) {
            addCriterion("s_addr <>", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrGreaterThan(String value) {
            addCriterion("s_addr >", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrGreaterThanOrEqualTo(String value) {
            addCriterion("s_addr >=", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrLessThan(String value) {
            addCriterion("s_addr <", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrLessThanOrEqualTo(String value) {
            addCriterion("s_addr <=", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrLike(String value) {
            addCriterion("s_addr like", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrNotLike(String value) {
            addCriterion("s_addr not like", value, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrIn(List<String> values) {
            addCriterion("s_addr in", values, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrNotIn(List<String> values) {
            addCriterion("s_addr not in", values, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrBetween(String value1, String value2) {
            addCriterion("s_addr between", value1, value2, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSAddrNotBetween(String value1, String value2) {
            addCriterion("s_addr not between", value1, value2, "sAddr");
            return (Criteria) this;
        }

        public Criteria andSPicIsNull() {
            addCriterion("s_pic is null");
            return (Criteria) this;
        }

        public Criteria andSPicIsNotNull() {
            addCriterion("s_pic is not null");
            return (Criteria) this;
        }

        public Criteria andSPicEqualTo(String value) {
            addCriterion("s_pic =", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicNotEqualTo(String value) {
            addCriterion("s_pic <>", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicGreaterThan(String value) {
            addCriterion("s_pic >", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicGreaterThanOrEqualTo(String value) {
            addCriterion("s_pic >=", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicLessThan(String value) {
            addCriterion("s_pic <", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicLessThanOrEqualTo(String value) {
            addCriterion("s_pic <=", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicLike(String value) {
            addCriterion("s_pic like", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicNotLike(String value) {
            addCriterion("s_pic not like", value, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicIn(List<String> values) {
            addCriterion("s_pic in", values, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicNotIn(List<String> values) {
            addCriterion("s_pic not in", values, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicBetween(String value1, String value2) {
            addCriterion("s_pic between", value1, value2, "sPic");
            return (Criteria) this;
        }

        public Criteria andSPicNotBetween(String value1, String value2) {
            addCriterion("s_pic not between", value1, value2, "sPic");
            return (Criteria) this;
        }

        public Criteria andSStateIsNull() {
            addCriterion("s_state is null");
            return (Criteria) this;
        }

        public Criteria andSStateIsNotNull() {
            addCriterion("s_state is not null");
            return (Criteria) this;
        }

        public Criteria andSStateEqualTo(String value) {
            addCriterion("s_state =", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateNotEqualTo(String value) {
            addCriterion("s_state <>", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateGreaterThan(String value) {
            addCriterion("s_state >", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateGreaterThanOrEqualTo(String value) {
            addCriterion("s_state >=", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateLessThan(String value) {
            addCriterion("s_state <", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateLessThanOrEqualTo(String value) {
            addCriterion("s_state <=", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateLike(String value) {
            addCriterion("s_state like", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateNotLike(String value) {
            addCriterion("s_state not like", value, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateIn(List<String> values) {
            addCriterion("s_state in", values, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateNotIn(List<String> values) {
            addCriterion("s_state not in", values, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateBetween(String value1, String value2) {
            addCriterion("s_state between", value1, value2, "sState");
            return (Criteria) this;
        }

        public Criteria andSStateNotBetween(String value1, String value2) {
            addCriterion("s_state not between", value1, value2, "sState");
            return (Criteria) this;
        }

        public Criteria andSInIsNull() {
            addCriterion("s_in is null");
            return (Criteria) this;
        }

        public Criteria andSInIsNotNull() {
            addCriterion("s_in is not null");
            return (Criteria) this;
        }

        public Criteria andSInEqualTo(String value) {
            addCriterion("s_in =", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInNotEqualTo(String value) {
            addCriterion("s_in <>", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInGreaterThan(String value) {
            addCriterion("s_in >", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInGreaterThanOrEqualTo(String value) {
            addCriterion("s_in >=", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInLessThan(String value) {
            addCriterion("s_in <", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInLessThanOrEqualTo(String value) {
            addCriterion("s_in <=", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInLike(String value) {
            addCriterion("s_in like", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInNotLike(String value) {
            addCriterion("s_in not like", value, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInIn(List<String> values) {
            addCriterion("s_in in", values, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInNotIn(List<String> values) {
            addCriterion("s_in not in", values, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInBetween(String value1, String value2) {
            addCriterion("s_in between", value1, value2, "sIn");
            return (Criteria) this;
        }

        public Criteria andSInNotBetween(String value1, String value2) {
            addCriterion("s_in not between", value1, value2, "sIn");
            return (Criteria) this;
        }

        public Criteria andSBirthIsNull() {
            addCriterion("s_birth is null");
            return (Criteria) this;
        }

        public Criteria andSBirthIsNotNull() {
            addCriterion("s_birth is not null");
            return (Criteria) this;
        }

        public Criteria andSBirthEqualTo(String value) {
            addCriterion("s_birth =", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthNotEqualTo(String value) {
            addCriterion("s_birth <>", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthGreaterThan(String value) {
            addCriterion("s_birth >", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthGreaterThanOrEqualTo(String value) {
            addCriterion("s_birth >=", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthLessThan(String value) {
            addCriterion("s_birth <", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthLessThanOrEqualTo(String value) {
            addCriterion("s_birth <=", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthLike(String value) {
            addCriterion("s_birth like", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthNotLike(String value) {
            addCriterion("s_birth not like", value, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthIn(List<String> values) {
            addCriterion("s_birth in", values, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthNotIn(List<String> values) {
            addCriterion("s_birth not in", values, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthBetween(String value1, String value2) {
            addCriterion("s_birth between", value1, value2, "sBirth");
            return (Criteria) this;
        }

        public Criteria andSBirthNotBetween(String value1, String value2) {
            addCriterion("s_birth not between", value1, value2, "sBirth");
            return (Criteria) this;
        }

        public Criteria andKey1IsNull() {
            addCriterion("key1 is null");
            return (Criteria) this;
        }

        public Criteria andKey1IsNotNull() {
            addCriterion("key1 is not null");
            return (Criteria) this;
        }

        public Criteria andKey1EqualTo(String value) {
            addCriterion("key1 =", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotEqualTo(String value) {
            addCriterion("key1 <>", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1GreaterThan(String value) {
            addCriterion("key1 >", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1GreaterThanOrEqualTo(String value) {
            addCriterion("key1 >=", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1LessThan(String value) {
            addCriterion("key1 <", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1LessThanOrEqualTo(String value) {
            addCriterion("key1 <=", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1Like(String value) {
            addCriterion("key1 like", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotLike(String value) {
            addCriterion("key1 not like", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1In(List<String> values) {
            addCriterion("key1 in", values, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotIn(List<String> values) {
            addCriterion("key1 not in", values, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1Between(String value1, String value2) {
            addCriterion("key1 between", value1, value2, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotBetween(String value1, String value2) {
            addCriterion("key1 not between", value1, value2, "key1");
            return (Criteria) this;
        }

        public Criteria andKey2IsNull() {
            addCriterion("key2 is null");
            return (Criteria) this;
        }

        public Criteria andKey2IsNotNull() {
            addCriterion("key2 is not null");
            return (Criteria) this;
        }

        public Criteria andKey2EqualTo(String value) {
            addCriterion("key2 =", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotEqualTo(String value) {
            addCriterion("key2 <>", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2GreaterThan(String value) {
            addCriterion("key2 >", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2GreaterThanOrEqualTo(String value) {
            addCriterion("key2 >=", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2LessThan(String value) {
            addCriterion("key2 <", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2LessThanOrEqualTo(String value) {
            addCriterion("key2 <=", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2Like(String value) {
            addCriterion("key2 like", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotLike(String value) {
            addCriterion("key2 not like", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2In(List<String> values) {
            addCriterion("key2 in", values, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotIn(List<String> values) {
            addCriterion("key2 not in", values, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2Between(String value1, String value2) {
            addCriterion("key2 between", value1, value2, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotBetween(String value1, String value2) {
            addCriterion("key2 not between", value1, value2, "key2");
            return (Criteria) this;
        }

        public Criteria andKey3IsNull() {
            addCriterion("key3 is null");
            return (Criteria) this;
        }

        public Criteria andKey3IsNotNull() {
            addCriterion("key3 is not null");
            return (Criteria) this;
        }

        public Criteria andKey3EqualTo(String value) {
            addCriterion("key3 =", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotEqualTo(String value) {
            addCriterion("key3 <>", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3GreaterThan(String value) {
            addCriterion("key3 >", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3GreaterThanOrEqualTo(String value) {
            addCriterion("key3 >=", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3LessThan(String value) {
            addCriterion("key3 <", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3LessThanOrEqualTo(String value) {
            addCriterion("key3 <=", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3Like(String value) {
            addCriterion("key3 like", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotLike(String value) {
            addCriterion("key3 not like", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3In(List<String> values) {
            addCriterion("key3 in", values, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotIn(List<String> values) {
            addCriterion("key3 not in", values, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3Between(String value1, String value2) {
            addCriterion("key3 between", value1, value2, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotBetween(String value1, String value2) {
            addCriterion("key3 not between", value1, value2, "key3");
            return (Criteria) this;
        }

        public Criteria andSInsIsNull() {
            addCriterion("s_ins is null");
            return (Criteria) this;
        }

        public Criteria andSInsIsNotNull() {
            addCriterion("s_ins is not null");
            return (Criteria) this;
        }

        public Criteria andSInsEqualTo(String value) {
            addCriterion("s_ins =", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsNotEqualTo(String value) {
            addCriterion("s_ins <>", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsGreaterThan(String value) {
            addCriterion("s_ins >", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsGreaterThanOrEqualTo(String value) {
            addCriterion("s_ins >=", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsLessThan(String value) {
            addCriterion("s_ins <", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsLessThanOrEqualTo(String value) {
            addCriterion("s_ins <=", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsLike(String value) {
            addCriterion("s_ins like", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsNotLike(String value) {
            addCriterion("s_ins not like", value, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsIn(List<String> values) {
            addCriterion("s_ins in", values, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsNotIn(List<String> values) {
            addCriterion("s_ins not in", values, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsBetween(String value1, String value2) {
            addCriterion("s_ins between", value1, value2, "sIns");
            return (Criteria) this;
        }

        public Criteria andSInsNotBetween(String value1, String value2) {
            addCriterion("s_ins not between", value1, value2, "sIns");
            return (Criteria) this;
        }

        public Criteria andSMajIsNull() {
            addCriterion("s_maj is null");
            return (Criteria) this;
        }

        public Criteria andSMajIsNotNull() {
            addCriterion("s_maj is not null");
            return (Criteria) this;
        }

        public Criteria andSMajEqualTo(String value) {
            addCriterion("s_maj =", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajNotEqualTo(String value) {
            addCriterion("s_maj <>", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajGreaterThan(String value) {
            addCriterion("s_maj >", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajGreaterThanOrEqualTo(String value) {
            addCriterion("s_maj >=", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajLessThan(String value) {
            addCriterion("s_maj <", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajLessThanOrEqualTo(String value) {
            addCriterion("s_maj <=", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajLike(String value) {
            addCriterion("s_maj like", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajNotLike(String value) {
            addCriterion("s_maj not like", value, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajIn(List<String> values) {
            addCriterion("s_maj in", values, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajNotIn(List<String> values) {
            addCriterion("s_maj not in", values, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajBetween(String value1, String value2) {
            addCriterion("s_maj between", value1, value2, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSMajNotBetween(String value1, String value2) {
            addCriterion("s_maj not between", value1, value2, "sMaj");
            return (Criteria) this;
        }

        public Criteria andSClaIsNull() {
            addCriterion("s_cla is null");
            return (Criteria) this;
        }

        public Criteria andSClaIsNotNull() {
            addCriterion("s_cla is not null");
            return (Criteria) this;
        }

        public Criteria andSClaEqualTo(String value) {
            addCriterion("s_cla =", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaNotEqualTo(String value) {
            addCriterion("s_cla <>", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaGreaterThan(String value) {
            addCriterion("s_cla >", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaGreaterThanOrEqualTo(String value) {
            addCriterion("s_cla >=", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaLessThan(String value) {
            addCriterion("s_cla <", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaLessThanOrEqualTo(String value) {
            addCriterion("s_cla <=", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaLike(String value) {
            addCriterion("s_cla like", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaNotLike(String value) {
            addCriterion("s_cla not like", value, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaIn(List<String> values) {
            addCriterion("s_cla in", values, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaNotIn(List<String> values) {
            addCriterion("s_cla not in", values, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaBetween(String value1, String value2) {
            addCriterion("s_cla between", value1, value2, "sCla");
            return (Criteria) this;
        }

        public Criteria andSClaNotBetween(String value1, String value2) {
            addCriterion("s_cla not between", value1, value2, "sCla");
            return (Criteria) this;
        }

        public Criteria andSAuthIsNull() {
            addCriterion("s_auth is null");
            return (Criteria) this;
        }

        public Criteria andSAuthIsNotNull() {
            addCriterion("s_auth is not null");
            return (Criteria) this;
        }

        public Criteria andSAuthEqualTo(String value) {
            addCriterion("s_auth =", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthNotEqualTo(String value) {
            addCriterion("s_auth <>", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthGreaterThan(String value) {
            addCriterion("s_auth >", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthGreaterThanOrEqualTo(String value) {
            addCriterion("s_auth >=", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthLessThan(String value) {
            addCriterion("s_auth <", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthLessThanOrEqualTo(String value) {
            addCriterion("s_auth <=", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthLike(String value) {
            addCriterion("s_auth like", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthNotLike(String value) {
            addCriterion("s_auth not like", value, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthIn(List<String> values) {
            addCriterion("s_auth in", values, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthNotIn(List<String> values) {
            addCriterion("s_auth not in", values, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthBetween(String value1, String value2) {
            addCriterion("s_auth between", value1, value2, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSAuthNotBetween(String value1, String value2) {
            addCriterion("s_auth not between", value1, value2, "sAuth");
            return (Criteria) this;
        }

        public Criteria andSPwdIsNull() {
            addCriterion("s_pwd is null");
            return (Criteria) this;
        }

        public Criteria andSPwdIsNotNull() {
            addCriterion("s_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andSPwdEqualTo(String value) {
            addCriterion("s_pwd =", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdNotEqualTo(String value) {
            addCriterion("s_pwd <>", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdGreaterThan(String value) {
            addCriterion("s_pwd >", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdGreaterThanOrEqualTo(String value) {
            addCriterion("s_pwd >=", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdLessThan(String value) {
            addCriterion("s_pwd <", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdLessThanOrEqualTo(String value) {
            addCriterion("s_pwd <=", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdLike(String value) {
            addCriterion("s_pwd like", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdNotLike(String value) {
            addCriterion("s_pwd not like", value, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdIn(List<String> values) {
            addCriterion("s_pwd in", values, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdNotIn(List<String> values) {
            addCriterion("s_pwd not in", values, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdBetween(String value1, String value2) {
            addCriterion("s_pwd between", value1, value2, "sPwd");
            return (Criteria) this;
        }

        public Criteria andSPwdNotBetween(String value1, String value2) {
            addCriterion("s_pwd not between", value1, value2, "sPwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stu
     *
     * @mbg.generated do_not_delete_during_merge Wed May 19 15:50:21 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}