package priv.sunyj.sms.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_job
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uJob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_sex
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_birth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_email
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_edu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uEdu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_phone
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String key3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_pwd
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uIns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_auth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String tAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_in
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String uIn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_num
     *
     * @return the value of t_user.u_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuNum() {
        return uNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_num
     *
     * @param uNum the value for t_user.u_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuNum(String uNum) {
        this.uNum = uNum == null ? null : uNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_name
     *
     * @return the value of t_user.u_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_name
     *
     * @param uName the value for t_user.u_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_job
     *
     * @return the value of t_user.u_job
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuJob() {
        return uJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_job
     *
     * @param uJob the value for t_user.u_job
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuJob(String uJob) {
        this.uJob = uJob == null ? null : uJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_sex
     *
     * @return the value of t_user.u_sex
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_sex
     *
     * @param uSex the value for t_user.u_sex
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuSex(String uSex) {
        this.uSex = uSex == null ? null : uSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_birth
     *
     * @return the value of t_user.u_birth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuBirth() {
        return uBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_birth
     *
     * @param uBirth the value for t_user.u_birth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuBirth(String uBirth) {
        this.uBirth = uBirth == null ? null : uBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_email
     *
     * @return the value of t_user.u_email
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_email
     *
     * @param uEmail the value for t_user.u_email
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_edu
     *
     * @return the value of t_user.u_edu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuEdu() {
        return uEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_edu
     *
     * @param uEdu the value for t_user.u_edu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuEdu(String uEdu) {
        this.uEdu = uEdu == null ? null : uEdu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_phone
     *
     * @return the value of t_user.u_phone
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_phone
     *
     * @param uPhone the value for t_user.u_phone
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone == null ? null : uPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.key1
     *
     * @return the value of t_user.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.key1
     *
     * @param key1 the value for t_user.key1
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.key2
     *
     * @return the value of t_user.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.key2
     *
     * @param key2 the value for t_user.key2
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey2(String key2) {
        this.key2 = key2 == null ? null : key2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.key3
     *
     * @return the value of t_user.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getKey3() {
        return key3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.key3
     *
     * @param key3 the value for t_user.key3
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setKey3(String key3) {
        this.key3 = key3 == null ? null : key3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_pwd
     *
     * @return the value of t_user.u_pwd
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_pwd
     *
     * @param uPwd the value for t_user.u_pwd
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuPwd(String uPwd) {
        this.uPwd = uPwd == null ? null : uPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_ins
     *
     * @return the value of t_user.u_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuIns() {
        return uIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_ins
     *
     * @param uIns the value for t_user.u_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuIns(String uIns) {
        this.uIns = uIns == null ? null : uIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_auth
     *
     * @return the value of t_user.t_auth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String gettAuth() {
        return tAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_auth
     *
     * @param tAuth the value for t_user.t_auth
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void settAuth(String tAuth) {
        this.tAuth = tAuth == null ? null : tAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_in
     *
     * @return the value of t_user.u_in
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getuIn() {
        return uIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_in
     *
     * @param uIn the value for t_user.u_in
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setuIn(String uIn) {
        this.uIn = uIn == null ? null : uIn.trim();
    }
}