package priv.sunyj.sms.bean;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public UserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUNumIsNull() {
            addCriterion("u_num is null");
            return (Criteria) this;
        }

        public Criteria andUNumIsNotNull() {
            addCriterion("u_num is not null");
            return (Criteria) this;
        }

        public Criteria andUNumEqualTo(String value) {
            addCriterion("u_num =", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumNotEqualTo(String value) {
            addCriterion("u_num <>", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumGreaterThan(String value) {
            addCriterion("u_num >", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumGreaterThanOrEqualTo(String value) {
            addCriterion("u_num >=", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumLessThan(String value) {
            addCriterion("u_num <", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumLessThanOrEqualTo(String value) {
            addCriterion("u_num <=", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumLike(String value) {
            addCriterion("u_num like", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumNotLike(String value) {
            addCriterion("u_num not like", value, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumIn(List<String> values) {
            addCriterion("u_num in", values, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumNotIn(List<String> values) {
            addCriterion("u_num not in", values, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumBetween(String value1, String value2) {
            addCriterion("u_num between", value1, value2, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNumNotBetween(String value1, String value2) {
            addCriterion("u_num not between", value1, value2, "uNum");
            return (Criteria) this;
        }

        public Criteria andUNameIsNull() {
            addCriterion("u_name is null");
            return (Criteria) this;
        }

        public Criteria andUNameIsNotNull() {
            addCriterion("u_name is not null");
            return (Criteria) this;
        }

        public Criteria andUNameEqualTo(String value) {
            addCriterion("u_name =", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotEqualTo(String value) {
            addCriterion("u_name <>", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThan(String value) {
            addCriterion("u_name >", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThanOrEqualTo(String value) {
            addCriterion("u_name >=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThan(String value) {
            addCriterion("u_name <", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThanOrEqualTo(String value) {
            addCriterion("u_name <=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLike(String value) {
            addCriterion("u_name like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotLike(String value) {
            addCriterion("u_name not like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameIn(List<String> values) {
            addCriterion("u_name in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotIn(List<String> values) {
            addCriterion("u_name not in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameBetween(String value1, String value2) {
            addCriterion("u_name between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotBetween(String value1, String value2) {
            addCriterion("u_name not between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUJobIsNull() {
            addCriterion("u_job is null");
            return (Criteria) this;
        }

        public Criteria andUJobIsNotNull() {
            addCriterion("u_job is not null");
            return (Criteria) this;
        }

        public Criteria andUJobEqualTo(String value) {
            addCriterion("u_job =", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobNotEqualTo(String value) {
            addCriterion("u_job <>", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobGreaterThan(String value) {
            addCriterion("u_job >", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobGreaterThanOrEqualTo(String value) {
            addCriterion("u_job >=", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobLessThan(String value) {
            addCriterion("u_job <", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobLessThanOrEqualTo(String value) {
            addCriterion("u_job <=", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobLike(String value) {
            addCriterion("u_job like", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobNotLike(String value) {
            addCriterion("u_job not like", value, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobIn(List<String> values) {
            addCriterion("u_job in", values, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobNotIn(List<String> values) {
            addCriterion("u_job not in", values, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobBetween(String value1, String value2) {
            addCriterion("u_job between", value1, value2, "uJob");
            return (Criteria) this;
        }

        public Criteria andUJobNotBetween(String value1, String value2) {
            addCriterion("u_job not between", value1, value2, "uJob");
            return (Criteria) this;
        }

        public Criteria andUSexIsNull() {
            addCriterion("u_sex is null");
            return (Criteria) this;
        }

        public Criteria andUSexIsNotNull() {
            addCriterion("u_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUSexEqualTo(String value) {
            addCriterion("u_sex =", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotEqualTo(String value) {
            addCriterion("u_sex <>", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexGreaterThan(String value) {
            addCriterion("u_sex >", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexGreaterThanOrEqualTo(String value) {
            addCriterion("u_sex >=", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexLessThan(String value) {
            addCriterion("u_sex <", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexLessThanOrEqualTo(String value) {
            addCriterion("u_sex <=", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexLike(String value) {
            addCriterion("u_sex like", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotLike(String value) {
            addCriterion("u_sex not like", value, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexIn(List<String> values) {
            addCriterion("u_sex in", values, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotIn(List<String> values) {
            addCriterion("u_sex not in", values, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexBetween(String value1, String value2) {
            addCriterion("u_sex between", value1, value2, "uSex");
            return (Criteria) this;
        }

        public Criteria andUSexNotBetween(String value1, String value2) {
            addCriterion("u_sex not between", value1, value2, "uSex");
            return (Criteria) this;
        }

        public Criteria andUBirthIsNull() {
            addCriterion("u_birth is null");
            return (Criteria) this;
        }

        public Criteria andUBirthIsNotNull() {
            addCriterion("u_birth is not null");
            return (Criteria) this;
        }

        public Criteria andUBirthEqualTo(String value) {
            addCriterion("u_birth =", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthNotEqualTo(String value) {
            addCriterion("u_birth <>", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthGreaterThan(String value) {
            addCriterion("u_birth >", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthGreaterThanOrEqualTo(String value) {
            addCriterion("u_birth >=", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthLessThan(String value) {
            addCriterion("u_birth <", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthLessThanOrEqualTo(String value) {
            addCriterion("u_birth <=", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthLike(String value) {
            addCriterion("u_birth like", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthNotLike(String value) {
            addCriterion("u_birth not like", value, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthIn(List<String> values) {
            addCriterion("u_birth in", values, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthNotIn(List<String> values) {
            addCriterion("u_birth not in", values, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthBetween(String value1, String value2) {
            addCriterion("u_birth between", value1, value2, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUBirthNotBetween(String value1, String value2) {
            addCriterion("u_birth not between", value1, value2, "uBirth");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNull() {
            addCriterion("u_email is null");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNotNull() {
            addCriterion("u_email is not null");
            return (Criteria) this;
        }

        public Criteria andUEmailEqualTo(String value) {
            addCriterion("u_email =", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotEqualTo(String value) {
            addCriterion("u_email <>", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThan(String value) {
            addCriterion("u_email >", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThanOrEqualTo(String value) {
            addCriterion("u_email >=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThan(String value) {
            addCriterion("u_email <", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThanOrEqualTo(String value) {
            addCriterion("u_email <=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLike(String value) {
            addCriterion("u_email like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotLike(String value) {
            addCriterion("u_email not like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailIn(List<String> values) {
            addCriterion("u_email in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotIn(List<String> values) {
            addCriterion("u_email not in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailBetween(String value1, String value2) {
            addCriterion("u_email between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotBetween(String value1, String value2) {
            addCriterion("u_email not between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEduIsNull() {
            addCriterion("u_edu is null");
            return (Criteria) this;
        }

        public Criteria andUEduIsNotNull() {
            addCriterion("u_edu is not null");
            return (Criteria) this;
        }

        public Criteria andUEduEqualTo(String value) {
            addCriterion("u_edu =", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduNotEqualTo(String value) {
            addCriterion("u_edu <>", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduGreaterThan(String value) {
            addCriterion("u_edu >", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduGreaterThanOrEqualTo(String value) {
            addCriterion("u_edu >=", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduLessThan(String value) {
            addCriterion("u_edu <", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduLessThanOrEqualTo(String value) {
            addCriterion("u_edu <=", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduLike(String value) {
            addCriterion("u_edu like", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduNotLike(String value) {
            addCriterion("u_edu not like", value, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduIn(List<String> values) {
            addCriterion("u_edu in", values, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduNotIn(List<String> values) {
            addCriterion("u_edu not in", values, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduBetween(String value1, String value2) {
            addCriterion("u_edu between", value1, value2, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUEduNotBetween(String value1, String value2) {
            addCriterion("u_edu not between", value1, value2, "uEdu");
            return (Criteria) this;
        }

        public Criteria andUPhoneIsNull() {
            addCriterion("u_phone is null");
            return (Criteria) this;
        }

        public Criteria andUPhoneIsNotNull() {
            addCriterion("u_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUPhoneEqualTo(String value) {
            addCriterion("u_phone =", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneNotEqualTo(String value) {
            addCriterion("u_phone <>", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneGreaterThan(String value) {
            addCriterion("u_phone >", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("u_phone >=", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneLessThan(String value) {
            addCriterion("u_phone <", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneLessThanOrEqualTo(String value) {
            addCriterion("u_phone <=", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneLike(String value) {
            addCriterion("u_phone like", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneNotLike(String value) {
            addCriterion("u_phone not like", value, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneIn(List<String> values) {
            addCriterion("u_phone in", values, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneNotIn(List<String> values) {
            addCriterion("u_phone not in", values, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneBetween(String value1, String value2) {
            addCriterion("u_phone between", value1, value2, "uPhone");
            return (Criteria) this;
        }

        public Criteria andUPhoneNotBetween(String value1, String value2) {
            addCriterion("u_phone not between", value1, value2, "uPhone");
            return (Criteria) this;
        }

        public Criteria andKey1IsNull() {
            addCriterion("key1 is null");
            return (Criteria) this;
        }

        public Criteria andKey1IsNotNull() {
            addCriterion("key1 is not null");
            return (Criteria) this;
        }

        public Criteria andKey1EqualTo(String value) {
            addCriterion("key1 =", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotEqualTo(String value) {
            addCriterion("key1 <>", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1GreaterThan(String value) {
            addCriterion("key1 >", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1GreaterThanOrEqualTo(String value) {
            addCriterion("key1 >=", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1LessThan(String value) {
            addCriterion("key1 <", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1LessThanOrEqualTo(String value) {
            addCriterion("key1 <=", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1Like(String value) {
            addCriterion("key1 like", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotLike(String value) {
            addCriterion("key1 not like", value, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1In(List<String> values) {
            addCriterion("key1 in", values, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotIn(List<String> values) {
            addCriterion("key1 not in", values, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1Between(String value1, String value2) {
            addCriterion("key1 between", value1, value2, "key1");
            return (Criteria) this;
        }

        public Criteria andKey1NotBetween(String value1, String value2) {
            addCriterion("key1 not between", value1, value2, "key1");
            return (Criteria) this;
        }

        public Criteria andKey2IsNull() {
            addCriterion("key2 is null");
            return (Criteria) this;
        }

        public Criteria andKey2IsNotNull() {
            addCriterion("key2 is not null");
            return (Criteria) this;
        }

        public Criteria andKey2EqualTo(String value) {
            addCriterion("key2 =", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotEqualTo(String value) {
            addCriterion("key2 <>", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2GreaterThan(String value) {
            addCriterion("key2 >", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2GreaterThanOrEqualTo(String value) {
            addCriterion("key2 >=", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2LessThan(String value) {
            addCriterion("key2 <", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2LessThanOrEqualTo(String value) {
            addCriterion("key2 <=", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2Like(String value) {
            addCriterion("key2 like", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotLike(String value) {
            addCriterion("key2 not like", value, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2In(List<String> values) {
            addCriterion("key2 in", values, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotIn(List<String> values) {
            addCriterion("key2 not in", values, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2Between(String value1, String value2) {
            addCriterion("key2 between", value1, value2, "key2");
            return (Criteria) this;
        }

        public Criteria andKey2NotBetween(String value1, String value2) {
            addCriterion("key2 not between", value1, value2, "key2");
            return (Criteria) this;
        }

        public Criteria andKey3IsNull() {
            addCriterion("key3 is null");
            return (Criteria) this;
        }

        public Criteria andKey3IsNotNull() {
            addCriterion("key3 is not null");
            return (Criteria) this;
        }

        public Criteria andKey3EqualTo(String value) {
            addCriterion("key3 =", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotEqualTo(String value) {
            addCriterion("key3 <>", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3GreaterThan(String value) {
            addCriterion("key3 >", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3GreaterThanOrEqualTo(String value) {
            addCriterion("key3 >=", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3LessThan(String value) {
            addCriterion("key3 <", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3LessThanOrEqualTo(String value) {
            addCriterion("key3 <=", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3Like(String value) {
            addCriterion("key3 like", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotLike(String value) {
            addCriterion("key3 not like", value, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3In(List<String> values) {
            addCriterion("key3 in", values, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotIn(List<String> values) {
            addCriterion("key3 not in", values, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3Between(String value1, String value2) {
            addCriterion("key3 between", value1, value2, "key3");
            return (Criteria) this;
        }

        public Criteria andKey3NotBetween(String value1, String value2) {
            addCriterion("key3 not between", value1, value2, "key3");
            return (Criteria) this;
        }

        public Criteria andUPwdIsNull() {
            addCriterion("u_pwd is null");
            return (Criteria) this;
        }

        public Criteria andUPwdIsNotNull() {
            addCriterion("u_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andUPwdEqualTo(String value) {
            addCriterion("u_pwd =", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotEqualTo(String value) {
            addCriterion("u_pwd <>", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdGreaterThan(String value) {
            addCriterion("u_pwd >", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdGreaterThanOrEqualTo(String value) {
            addCriterion("u_pwd >=", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLessThan(String value) {
            addCriterion("u_pwd <", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLessThanOrEqualTo(String value) {
            addCriterion("u_pwd <=", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLike(String value) {
            addCriterion("u_pwd like", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotLike(String value) {
            addCriterion("u_pwd not like", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdIn(List<String> values) {
            addCriterion("u_pwd in", values, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotIn(List<String> values) {
            addCriterion("u_pwd not in", values, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdBetween(String value1, String value2) {
            addCriterion("u_pwd between", value1, value2, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotBetween(String value1, String value2) {
            addCriterion("u_pwd not between", value1, value2, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUInsIsNull() {
            addCriterion("u_ins is null");
            return (Criteria) this;
        }

        public Criteria andUInsIsNotNull() {
            addCriterion("u_ins is not null");
            return (Criteria) this;
        }

        public Criteria andUInsEqualTo(String value) {
            addCriterion("u_ins =", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsNotEqualTo(String value) {
            addCriterion("u_ins <>", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsGreaterThan(String value) {
            addCriterion("u_ins >", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsGreaterThanOrEqualTo(String value) {
            addCriterion("u_ins >=", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsLessThan(String value) {
            addCriterion("u_ins <", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsLessThanOrEqualTo(String value) {
            addCriterion("u_ins <=", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsLike(String value) {
            addCriterion("u_ins like", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsNotLike(String value) {
            addCriterion("u_ins not like", value, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsIn(List<String> values) {
            addCriterion("u_ins in", values, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsNotIn(List<String> values) {
            addCriterion("u_ins not in", values, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsBetween(String value1, String value2) {
            addCriterion("u_ins between", value1, value2, "uIns");
            return (Criteria) this;
        }

        public Criteria andUInsNotBetween(String value1, String value2) {
            addCriterion("u_ins not between", value1, value2, "uIns");
            return (Criteria) this;
        }

        public Criteria andTAuthIsNull() {
            addCriterion("t_auth is null");
            return (Criteria) this;
        }

        public Criteria andTAuthIsNotNull() {
            addCriterion("t_auth is not null");
            return (Criteria) this;
        }

        public Criteria andTAuthEqualTo(String value) {
            addCriterion("t_auth =", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthNotEqualTo(String value) {
            addCriterion("t_auth <>", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthGreaterThan(String value) {
            addCriterion("t_auth >", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthGreaterThanOrEqualTo(String value) {
            addCriterion("t_auth >=", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthLessThan(String value) {
            addCriterion("t_auth <", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthLessThanOrEqualTo(String value) {
            addCriterion("t_auth <=", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthLike(String value) {
            addCriterion("t_auth like", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthNotLike(String value) {
            addCriterion("t_auth not like", value, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthIn(List<String> values) {
            addCriterion("t_auth in", values, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthNotIn(List<String> values) {
            addCriterion("t_auth not in", values, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthBetween(String value1, String value2) {
            addCriterion("t_auth between", value1, value2, "tAuth");
            return (Criteria) this;
        }

        public Criteria andTAuthNotBetween(String value1, String value2) {
            addCriterion("t_auth not between", value1, value2, "tAuth");
            return (Criteria) this;
        }

        public Criteria andUInIsNull() {
            addCriterion("u_in is null");
            return (Criteria) this;
        }

        public Criteria andUInIsNotNull() {
            addCriterion("u_in is not null");
            return (Criteria) this;
        }

        public Criteria andUInEqualTo(String value) {
            addCriterion("u_in =", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInNotEqualTo(String value) {
            addCriterion("u_in <>", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInGreaterThan(String value) {
            addCriterion("u_in >", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInGreaterThanOrEqualTo(String value) {
            addCriterion("u_in >=", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInLessThan(String value) {
            addCriterion("u_in <", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInLessThanOrEqualTo(String value) {
            addCriterion("u_in <=", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInLike(String value) {
            addCriterion("u_in like", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInNotLike(String value) {
            addCriterion("u_in not like", value, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInIn(List<String> values) {
            addCriterion("u_in in", values, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInNotIn(List<String> values) {
            addCriterion("u_in not in", values, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInBetween(String value1, String value2) {
            addCriterion("u_in between", value1, value2, "uIn");
            return (Criteria) this;
        }

        public Criteria andUInNotBetween(String value1, String value2) {
            addCriterion("u_in not between", value1, value2, "uIn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated do_not_delete_during_merge Wed May 19 15:50:21 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}