package priv.sunyj.sms.bean;

public class XuanKe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.s_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.s_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String sNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cIns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.c_gra
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cGra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.c_time
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.week
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xuanke.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    private String cla;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.s_name
     *
     * @return the value of t_xuanke.s_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.s_name
     *
     * @param sName the value for t_xuanke.s_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.s_num
     *
     * @return the value of t_xuanke.s_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getsNum() {
        return sNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.s_num
     *
     * @param sNum the value for t_xuanke.s_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setsNum(String sNum) {
        this.sNum = sNum == null ? null : sNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.c_name
     *
     * @return the value of t_xuanke.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.c_name
     *
     * @param cName the value for t_xuanke.c_name
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.c_num
     *
     * @return the value of t_xuanke.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcNum() {
        return cNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.c_num
     *
     * @param cNum the value for t_xuanke.c_num
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcNum(String cNum) {
        this.cNum = cNum == null ? null : cNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.c_ins
     *
     * @return the value of t_xuanke.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcIns() {
        return cIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.c_ins
     *
     * @param cIns the value for t_xuanke.c_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcIns(String cIns) {
        this.cIns = cIns == null ? null : cIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.c_gra
     *
     * @return the value of t_xuanke.c_gra
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcGra() {
        return cGra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.c_gra
     *
     * @param cGra the value for t_xuanke.c_gra
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcGra(String cGra) {
        this.cGra = cGra == null ? null : cGra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.c_time
     *
     * @return the value of t_xuanke.c_time
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.c_time
     *
     * @param cTime the value for t_xuanke.c_time
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setcTime(String cTime) {
        this.cTime = cTime == null ? null : cTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.week
     *
     * @return the value of t_xuanke.week
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.week
     *
     * @param week the value for t_xuanke.week
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xuanke.cla
     *
     * @return the value of t_xuanke.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getCla() {
        return cla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xuanke.cla
     *
     * @param cla the value for t_xuanke.cla
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setCla(String cla) {
        this.cla = cla == null ? null : cla.trim();
    }
}