package priv.sunyj.sms.bean;

import java.util.ArrayList;
import java.util.List;

public class XuanKeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public XuanKeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSNameIsNull() {
            addCriterion("s_name is null");
            return (Criteria) this;
        }

        public Criteria andSNameIsNotNull() {
            addCriterion("s_name is not null");
            return (Criteria) this;
        }

        public Criteria andSNameEqualTo(String value) {
            addCriterion("s_name =", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotEqualTo(String value) {
            addCriterion("s_name <>", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThan(String value) {
            addCriterion("s_name >", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThanOrEqualTo(String value) {
            addCriterion("s_name >=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThan(String value) {
            addCriterion("s_name <", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThanOrEqualTo(String value) {
            addCriterion("s_name <=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLike(String value) {
            addCriterion("s_name like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotLike(String value) {
            addCriterion("s_name not like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameIn(List<String> values) {
            addCriterion("s_name in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotIn(List<String> values) {
            addCriterion("s_name not in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameBetween(String value1, String value2) {
            addCriterion("s_name between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotBetween(String value1, String value2) {
            addCriterion("s_name not between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSNumIsNull() {
            addCriterion("s_num is null");
            return (Criteria) this;
        }

        public Criteria andSNumIsNotNull() {
            addCriterion("s_num is not null");
            return (Criteria) this;
        }

        public Criteria andSNumEqualTo(String value) {
            addCriterion("s_num =", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotEqualTo(String value) {
            addCriterion("s_num <>", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumGreaterThan(String value) {
            addCriterion("s_num >", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumGreaterThanOrEqualTo(String value) {
            addCriterion("s_num >=", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumLessThan(String value) {
            addCriterion("s_num <", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumLessThanOrEqualTo(String value) {
            addCriterion("s_num <=", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumLike(String value) {
            addCriterion("s_num like", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotLike(String value) {
            addCriterion("s_num not like", value, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumIn(List<String> values) {
            addCriterion("s_num in", values, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotIn(List<String> values) {
            addCriterion("s_num not in", values, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumBetween(String value1, String value2) {
            addCriterion("s_num between", value1, value2, "sNum");
            return (Criteria) this;
        }

        public Criteria andSNumNotBetween(String value1, String value2) {
            addCriterion("s_num not between", value1, value2, "sNum");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNumIsNull() {
            addCriterion("c_num is null");
            return (Criteria) this;
        }

        public Criteria andCNumIsNotNull() {
            addCriterion("c_num is not null");
            return (Criteria) this;
        }

        public Criteria andCNumEqualTo(String value) {
            addCriterion("c_num =", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotEqualTo(String value) {
            addCriterion("c_num <>", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumGreaterThan(String value) {
            addCriterion("c_num >", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumGreaterThanOrEqualTo(String value) {
            addCriterion("c_num >=", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumLessThan(String value) {
            addCriterion("c_num <", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumLessThanOrEqualTo(String value) {
            addCriterion("c_num <=", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumLike(String value) {
            addCriterion("c_num like", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotLike(String value) {
            addCriterion("c_num not like", value, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumIn(List<String> values) {
            addCriterion("c_num in", values, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotIn(List<String> values) {
            addCriterion("c_num not in", values, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumBetween(String value1, String value2) {
            addCriterion("c_num between", value1, value2, "cNum");
            return (Criteria) this;
        }

        public Criteria andCNumNotBetween(String value1, String value2) {
            addCriterion("c_num not between", value1, value2, "cNum");
            return (Criteria) this;
        }

        public Criteria andCInsIsNull() {
            addCriterion("c_ins is null");
            return (Criteria) this;
        }

        public Criteria andCInsIsNotNull() {
            addCriterion("c_ins is not null");
            return (Criteria) this;
        }

        public Criteria andCInsEqualTo(String value) {
            addCriterion("c_ins =", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotEqualTo(String value) {
            addCriterion("c_ins <>", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsGreaterThan(String value) {
            addCriterion("c_ins >", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsGreaterThanOrEqualTo(String value) {
            addCriterion("c_ins >=", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsLessThan(String value) {
            addCriterion("c_ins <", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsLessThanOrEqualTo(String value) {
            addCriterion("c_ins <=", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsLike(String value) {
            addCriterion("c_ins like", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotLike(String value) {
            addCriterion("c_ins not like", value, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsIn(List<String> values) {
            addCriterion("c_ins in", values, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotIn(List<String> values) {
            addCriterion("c_ins not in", values, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsBetween(String value1, String value2) {
            addCriterion("c_ins between", value1, value2, "cIns");
            return (Criteria) this;
        }

        public Criteria andCInsNotBetween(String value1, String value2) {
            addCriterion("c_ins not between", value1, value2, "cIns");
            return (Criteria) this;
        }

        public Criteria andCGraIsNull() {
            addCriterion("c_gra is null");
            return (Criteria) this;
        }

        public Criteria andCGraIsNotNull() {
            addCriterion("c_gra is not null");
            return (Criteria) this;
        }

        public Criteria andCGraEqualTo(String value) {
            addCriterion("c_gra =", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraNotEqualTo(String value) {
            addCriterion("c_gra <>", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraGreaterThan(String value) {
            addCriterion("c_gra >", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraGreaterThanOrEqualTo(String value) {
            addCriterion("c_gra >=", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraLessThan(String value) {
            addCriterion("c_gra <", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraLessThanOrEqualTo(String value) {
            addCriterion("c_gra <=", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraLike(String value) {
            addCriterion("c_gra like", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraNotLike(String value) {
            addCriterion("c_gra not like", value, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraIn(List<String> values) {
            addCriterion("c_gra in", values, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraNotIn(List<String> values) {
            addCriterion("c_gra not in", values, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraBetween(String value1, String value2) {
            addCriterion("c_gra between", value1, value2, "cGra");
            return (Criteria) this;
        }

        public Criteria andCGraNotBetween(String value1, String value2) {
            addCriterion("c_gra not between", value1, value2, "cGra");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNull() {
            addCriterion("c_time is null");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNotNull() {
            addCriterion("c_time is not null");
            return (Criteria) this;
        }

        public Criteria andCTimeEqualTo(String value) {
            addCriterion("c_time =", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotEqualTo(String value) {
            addCriterion("c_time <>", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThan(String value) {
            addCriterion("c_time >", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThanOrEqualTo(String value) {
            addCriterion("c_time >=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThan(String value) {
            addCriterion("c_time <", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThanOrEqualTo(String value) {
            addCriterion("c_time <=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLike(String value) {
            addCriterion("c_time like", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotLike(String value) {
            addCriterion("c_time not like", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeIn(List<String> values) {
            addCriterion("c_time in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotIn(List<String> values) {
            addCriterion("c_time not in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeBetween(String value1, String value2) {
            addCriterion("c_time between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotBetween(String value1, String value2) {
            addCriterion("c_time not between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andWeekIsNull() {
            addCriterion("week is null");
            return (Criteria) this;
        }

        public Criteria andWeekIsNotNull() {
            addCriterion("week is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEqualTo(String value) {
            addCriterion("week =", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotEqualTo(String value) {
            addCriterion("week <>", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThan(String value) {
            addCriterion("week >", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThanOrEqualTo(String value) {
            addCriterion("week >=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThan(String value) {
            addCriterion("week <", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThanOrEqualTo(String value) {
            addCriterion("week <=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLike(String value) {
            addCriterion("week like", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotLike(String value) {
            addCriterion("week not like", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekIn(List<String> values) {
            addCriterion("week in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotIn(List<String> values) {
            addCriterion("week not in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekBetween(String value1, String value2) {
            addCriterion("week between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotBetween(String value1, String value2) {
            addCriterion("week not between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andClaIsNull() {
            addCriterion("cla is null");
            return (Criteria) this;
        }

        public Criteria andClaIsNotNull() {
            addCriterion("cla is not null");
            return (Criteria) this;
        }

        public Criteria andClaEqualTo(String value) {
            addCriterion("cla =", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaNotEqualTo(String value) {
            addCriterion("cla <>", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaGreaterThan(String value) {
            addCriterion("cla >", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaGreaterThanOrEqualTo(String value) {
            addCriterion("cla >=", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaLessThan(String value) {
            addCriterion("cla <", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaLessThanOrEqualTo(String value) {
            addCriterion("cla <=", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaLike(String value) {
            addCriterion("cla like", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaNotLike(String value) {
            addCriterion("cla not like", value, "cla");
            return (Criteria) this;
        }

        public Criteria andClaIn(List<String> values) {
            addCriterion("cla in", values, "cla");
            return (Criteria) this;
        }

        public Criteria andClaNotIn(List<String> values) {
            addCriterion("cla not in", values, "cla");
            return (Criteria) this;
        }

        public Criteria andClaBetween(String value1, String value2) {
            addCriterion("cla between", value1, value2, "cla");
            return (Criteria) this;
        }

        public Criteria andClaNotBetween(String value1, String value2) {
            addCriterion("cla not between", value1, value2, "cla");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_xuanke
     *
     * @mbg.generated do_not_delete_during_merge Wed May 19 15:50:21 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}