package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.AuthPower;
import priv.sunyj.sms.bean.AuthPowerExample;

public interface AuthPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    long countByExample(AuthPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByExample(AuthPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insert(AuthPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insertSelective(AuthPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    List<AuthPower> selectByExample(AuthPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") AuthPower record, @Param("example") AuthPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExample(@Param("record") AuthPower record, @Param("example") AuthPowerExample example);
}