package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.InsMaj;
import priv.sunyj.sms.bean.InsMajExample;

public interface InsMajMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins_maj
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    long countByExample(InsMajExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins_maj
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int deleteByExample(InsMajExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins_maj
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int insert(InsMaj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins_maj
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int insertSelective(InsMaj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins_maj
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    List<InsMaj> selectByExample(InsMajExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins_maj
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") InsMaj record, @Param("example") InsMajExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins_maj
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int updateByExample(@Param("record") InsMaj record, @Param("example") InsMajExample example);
}