package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.Institution;
import priv.sunyj.sms.bean.InstitutionExample;

public interface InstitutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    long countByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByPrimaryKey(String iNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insert(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insertSelective(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    List<Institution> selectByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    Institution selectByPrimaryKey(String iNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") Institution record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExample(@Param("record") Institution record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByPrimaryKeySelective(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ins
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByPrimaryKey(Institution record);
}