package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.MajCla;
import priv.sunyj.sms.bean.MajClaExample;

public interface MajClaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    long countByExample(MajClaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int deleteByExample(MajClaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int insert(MajCla record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int insertSelective(MajCla record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    List<MajCla> selectByExample(MajClaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") MajCla record, @Param("example") MajClaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_maj_cla
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int updateByExample(@Param("record") MajCla record, @Param("example") MajClaExample example);
}