package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.Pow1Pow2;
import priv.sunyj.sms.bean.Pow1Pow2Example;

public interface Pow1Pow2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pow1_pow2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    long countByExample(Pow1Pow2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pow1_pow2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int deleteByExample(Pow1Pow2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pow1_pow2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int insert(Pow1Pow2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pow1_pow2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int insertSelective(Pow1Pow2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pow1_pow2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    List<Pow1Pow2> selectByExample(Pow1Pow2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pow1_pow2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") Pow1Pow2 record, @Param("example") Pow1Pow2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pow1_pow2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByExample(@Param("record") Pow1Pow2 record, @Param("example") Pow1Pow2Example example);
}