package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.Power;
import priv.sunyj.sms.bean.PowerExample;

public interface PowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    long countByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByPrimaryKey(String pNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insert(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insertSelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    List<Power> selectByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    Power selectByPrimaryKey(String pNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") Power record, @Param("example") PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExample(@Param("record") Power record, @Param("example") PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByPrimaryKeySelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByPrimaryKey(Power record);
}