package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.Power2;
import priv.sunyj.sms.bean.Power2Example;

public interface Power2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    long countByExample(Power2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int deleteByExample(Power2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int deleteByPrimaryKey(String pNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int insert(Power2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int insertSelective(Power2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    List<Power2> selectByExample(Power2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    Power2 selectByPrimaryKey(String pNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") Power2 record, @Param("example") Power2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByExample(@Param("record") Power2 record, @Param("example") Power2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByPrimaryKeySelective(Power2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_2
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByPrimaryKey(Power2 record);
}