package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.Power1;
import priv.sunyj.sms.bean.Power1Example;

public interface Power1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    long countByExample(Power1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int deleteByExample(Power1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int deleteByPrimaryKey(String pNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int insert(Power1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int insertSelective(Power1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    List<Power1> selectByExample(Power1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    Power1 selectByPrimaryKey(String pNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") Power1 record, @Param("example") Power1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByExample(@Param("record") Power1 record, @Param("example") Power1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByPrimaryKeySelective(Power1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_power_1
     *
     * @mbg.generated Fri Apr 23 00:19:08 CST 2021
     */
    int updateByPrimaryKey(Power1 record);
}