package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.StuCour;
import priv.sunyj.sms.bean.StuCourExample;

public interface StuCourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_cour
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    long countByExample(StuCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_cour
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByExample(StuCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_cour
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insert(StuCour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_cour
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insertSelective(StuCour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_cour
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    List<StuCour> selectByExample(StuCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_cour
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") StuCour record, @Param("example") StuCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_cour
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExample(@Param("record") StuCour record, @Param("example") StuCourExample example);
}