package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.Student;
import priv.sunyj.sms.bean.StudentExample;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByPrimaryKey(String sNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    Student selectByPrimaryKey(String sNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByPrimaryKey(Student record);
}