package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.UserCour;
import priv.sunyj.sms.bean.UserCourExample;

public interface UserCourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_cour
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    long countByExample(UserCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_cour
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int deleteByExample(UserCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_cour
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int insert(UserCour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_cour
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int insertSelective(UserCour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_cour
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    List<UserCour> selectByExample(UserCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_cour
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserCour record, @Param("example") UserCourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_cour
     *
     * @mbg.generated Tue Apr 27 19:50:03 CST 2021
     */
    int updateByExample(@Param("record") UserCour record, @Param("example") UserCourExample example);
}