package priv.sunyj.sms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.sunyj.sms.bean.XuanKe;
import priv.sunyj.sms.bean.XuanKeExample;

public interface XuanKeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    long countByExample(XuanKeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int deleteByExample(XuanKeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insert(XuanKe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int insertSelective(XuanKe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    List<XuanKe> selectByExample(XuanKeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") XuanKe record, @Param("example") XuanKeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xuanke
     *
     * @mbg.generated Wed May 19 15:50:21 CST 2021
     */
    int updateByExample(@Param("record") XuanKe record, @Param("example") XuanKeExample example);
}